version: "3.5"

services:
  aca-py:
    # Use any version you like
    image: bcgovimages/aries-cloudagent:py36-1.15-0_0.5.6
    ports:
      - "3001:3001"
      - "3000:3000"
    entrypoint: aca-py start --endpoint http://localhost:3000 --inbound-transport http 0.0.0.0 3000 --outbound-transport http --webhook-url http://webhook-server:1080 --admin 0.0.0.0 3001 --admin-insecure-mode --no-ledger

  webhook-server:
    build: .
    ports:
      - 1080:1080
